server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '0719'
    url: jdbc:postgresql://localhost:5432/postgres
  thymeleaf:
    cache: false

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  mvc:
    locale: ko_KR
    locale-resolver: fixed

  task:
    scheduling:
      pool:
        size: 10


slack:
  bot-token: "-"
  signing-secret: ${SLACK_SIGNING_SECRET}
  postMessageUrl: "https://slack.com/api/chat.postMessage"
  channel:
    monitor: "#일반"

logging:
  level:
    org.hibernate.sql: debug
